//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LicenseGeneratorForCCIERantsPhoneControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LicenseGeneratorForCCIERantsPhoneControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DSAKeyValue&gt;&lt;P&gt;s3v9546xYFZG5Y68km4E7GSJa9ZBG99A3Ehljtmm/BVyPHoC6E0Bj02kvcm4C4Iy8+i7boiTCn66gtGwhLCJKdeSFipPg0ZfoJV4FW06PisGzBCgJfKrXv1kJAB4ezcr+fB4Xa0K1ApiabyvHoUO8ZnNeVz5uqhJwYPpW12VZQc=&lt;/P&gt;&lt;Q&gt;5QCSSJJORaK5WSMvxp1s7QEDPsM=&lt;/Q&gt;&lt;G&gt;JfnE60hbBB8HPGSkcSVRO/Ez4FOQSwPx2pcthzjnEgzXm694ii0e54+sou5VVqU7Y2WlbS3xdvfmhQhPpha5Cfs9SzSVNIqORRMruIwvaiEWUuoOU9F5rGVqOiFw1wqAYkJ7gPIsWRp5xM4CnFQeDzPIuktb+H8WASpuBK/Cjw4=&lt;/G&gt;&lt;Y&gt;IVfEYzwRWTWdl3gvidfBK5bo48ssgcjRVam84nJDcMrVleAt77nje6rt/J+knFj73p0ssrWpWDM/MlBewr603WH/9UTaVCqi6sE19qw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string privateKey {
            get {
                return ResourceManager.GetString("privateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DSAKeyValue&gt;&lt;P&gt;s3v9546xYFZG5Y68km4E7GSJa9ZBG99A3Ehljtmm/BVyPHoC6E0Bj02kvcm4C4Iy8+i7boiTCn66gtGwhLCJKdeSFipPg0ZfoJV4FW06PisGzBCgJfKrXv1kJAB4ezcr+fB4Xa0K1ApiabyvHoUO8ZnNeVz5uqhJwYPpW12VZQc=&lt;/P&gt;&lt;Q&gt;5QCSSJJORaK5WSMvxp1s7QEDPsM=&lt;/Q&gt;&lt;G&gt;JfnE60hbBB8HPGSkcSVRO/Ez4FOQSwPx2pcthzjnEgzXm694ii0e54+sou5VVqU7Y2WlbS3xdvfmhQhPpha5Cfs9SzSVNIqORRMruIwvaiEWUuoOU9F5rGVqOiFw1wqAYkJ7gPIsWRp5xM4CnFQeDzPIuktb+H8WASpuBK/Cjw4=&lt;/G&gt;&lt;Y&gt;IVfEYzwRWTWdl3gvidfBK5bo48ssgcjRVam84nJDcMrVleAt77nje6rt/J+knFj73p0ssrWpWDM/MlBewr603WH/9UTaVCqi6sE19qw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xmlMethod {
            get {
                return ResourceManager.GetString("xmlMethod", resourceCulture);
            }
        }
    }
}
